AMWA-TV/nmos-testing

GenericTest.py, IS0401Test.py, IS0402Test.py, IS0501Test.py, TestResult.py, nmos-test.py, static/js/script.js, templates/index.html, templates/result.html
Also adds a unique name for each test in the results page.
Resolves #3
=> Permit tests to be run individually where possible

GenericTest.py, IS04Utils.py, IS0501Test.py, IS0502Test.py, IS05Utils.py, NMOSUtils.py, TestHelper.py
Putting this here purely as an indicator of work in progress and in case it's of interest. Some of the IS-05 interaction methods need refactoring into another class to make them available to multiple test sets, however this should eventually provide a way to test the IS-04 version increments (and subscription changes).
At present this *should* check that the IS-04 version changes, however it's not failing on my test Node, so either it's having a bad day or it's found a bug!
=> Test IS-04 version increments when IS-05 activated

IS0402Test.py
Added downgrade_resource functionality
Implemented in basic resource registering tests
=> Added support for v1.0 and v1.1 in TestIS0402

GenericTest.py, IS0401Test.py, IS0402Test.py, IS0501Test.py, IS0502Test.py, IS05Utils.py, NMOSUtils.py, nmos-test.py
Work in progress. Still requires testing of subscription to an NMOS and non-NMOS Sender/Receiver mcast/ucast.
=> is0502: add first step in testing IS-04 subscription objects

IS0401Test.py
Add missing import (maybe got lost in 88dc69637eae851b733322d08373438a3d05b9db?)
=> Add missing import 

IS0402Test.py
Adding tests to verify correct result code for updating resources.
=> Adding tests for updating resources

Config.py, IS0402Test.py
Added a test: node + sub resources should be removed after a given timeout because of missing heartbeats
=> Add test  garbage collection

GenericTest.py, IS0501Test.py, IS05Utils.py
Work in progress to test the current state of the v1.1-dev branch
=> is0501: update testing for v1.1 development branch

IS0402Test.py, TestHelper.py, requirements.txt
Here is the big one about the websocket events. I had to modify the original source from our reg-test-suite quite a lot, I hope took everything into account..
Improvements and comments are welcome.
=> Added test websocket events

IS0402Test.py
Error found in review of PR #66
Updated in all remaining tests.
=> Fixed wrong version check < 2.0

IS0402Test.py, ReadMe.md, TestResult.py, static/css/style.css, templates/result.html
I'd prefer a different word to 'optional'. Suggestions welcome. Alternative two new TestResult states could be added for each of SHOULD and MAY, but that may be over the top.
Perhaps 'Not Implemented'?
=> Add test result case for SHOULD/MAY aspects of specs. Resolves #86

IS0401Test.py, Registry.py, nmos-test.py
Work in progress. Should allow testing of failover and priorities etc
=> Add capability to host multiple Registration APIs

Config.py, IS0401Test.py, IS0402Test.py
... and add a constant for the heartbeat interval as well.
=> Allow same uncertainty in the garbage collection interval, as for heartbeats

IS05Utils.py
=> is0502: avoid validation errors between staged/active dest port

IS0401Test.py, IS0402Test.py, IS0403Test.py
=> Fix partial match of ip address or port

IS0401Test.py, IS0402Test.py
As-yet untested additions to support the proposed PR https://github.com/AMWA-TV/nmos-discovery-registration/pull/71 for IS-04's Registration API
=> mdns: advertise and detect new service type for v1.3

IS0401Test.py, IS0402Test.py
I've not added these exceptions for the pagination/downgrade tests yet as they're currently manual.
=> is04: add handling for 501 codes introduced in v1.3

templates/index.html
=> index: add warning when JavaScript is disabled

ReadMe.md, setup.py
=> Updated readme (see #135)

Specification.py
This is a little hacky, but works around the problem for now. A better approach to this would be to fix ramlfications directly which I hope to do at a later date...
=> Fix detection of RAML 1.0 global types. Resolves #78

IS0401Test.py
This removes test_06 which is now covered by other tests. I haven't re-numbered things as yet. Happy to do so if preferred.
=> is0401: remove unnecessary test_06

IS0402Test.py, NMOSUtils.py
Adding this as a placeholder as I intend to work on it next.
=> Add support for downgrade queries

GenericTest.py, IS0402Test.py, IS0501Test.py, Patches.py, ReadMe.md, Specification.py, TestHelper.py
If this works out I'll remove any other uses of RefResolver and similar schema de-referencing as part of this PR.
Hopefully Resolves #134
=> is0501: use load_resolved_schema rather than RefResolver

nmos-test.py, static/js/script.js, templates/index.html, templates/result.html
Should resolve #128 
Tested with Firefox 65.0 and Chrome Version 72.0.3626.96 (although I did not have this issue with Chrome in first place).
Interested in other browsers (/versions) :)
=> Added no-cache, no-store to repsonse header

GenericTest.py, IS0402Test.py, IS0501Test.py
=> Ensure all schema validation includes a format checker

IS0401Test.py
=> Check that clocks and interfaces use unique names, which match Sources/Senders/Receivers

GenericTest.py, nmos-test.py, static/css/style.css, static/js/result_script.js, static/js/script.js, templates/index.html, templates/result.html
* repeatable tests from the 'result' page, including ability to just re-run failed tests (though 'auto' is something of a challenge!)
* multi-select tests on the 'index' page
* changes to the underlying test runner to allow a list of test cases to be passed in
Resolves #150.
=> Interactive test harness improvements

IS0402Test.py
A few minor linting errors I failed to catch in the original pagination review. Shouldn't make any functional difference, just makes my editor a little happier.
=> is0402: fix various minor linting errors

Config.py, IS0402Test.py
Work in progress...
Resolves #144
=> Advanced testing of basic/RQL/downgrade/ancestry queries

DNS.py
Follow-up to #125, while debugging an issue with unicast DNS-SD.
=> Just a few more prints in DNS.py

IS0402Test.py
And a lot of unfortunate whitespace/line re-wrapping as a result. 😒
Resolves #176. Other approaches are available. 😉
=> Use try-finally to ensure websockets are closed after an exception or early return

IS0402Test.py
Resolves #172 
This will make more sense once the first HTTPS PR is merged, as it's based on top of it.
=> Refactor Query API subscription requests

IS0402Test.py
Could probably _usually_ push the `try...except json.decoder.JSONDecodeError` inside `do_request` but perhaps not always... and most uses already have the `try...except` so this just adds the missing ones.
=> Avoid remaining json.decoder.JSONDecodeError exceptions from bad responses

nmos-test.py, templates/index.html, templates/result.html
Resolves #185.
Appreciate a couple of checks on other browsers. I've tried Windows Chrome 72 and IE 11.
=> Add cache-busting for the project CSS and JavaScript files

IS0402Test.py, static/css/style.css
120 fewer lines of code to maintain.
Precursor to attempting to make all test cases in this test suite independent.
=> IS0402Test refactor

static/css/style.css, static/js/result_script.js, templates/result.html
…so that re-running a selection of the test cases is easier when there are lots to choose from!
=> Make the table header (now including the 'Run' button) sticky

IS0402Test.py
Not sure how I managed this one, but a case of picking from the wrong object resulting in an unhandled exception.
=> is0402: fix error in refactoring

IS0402Test.py
Argh, didn't hit save before committing e99e16f71177246ccd185e55a90cdc0ff2233a67
=> More haste, less speed

IS0402Test.py
=> IS0402: Make all test cases independently runnable (no @test_depends)

nmos-test.py
Hopefully resolves #208 for @Genri1441.
=> Pretty-print and include the class name in the JUnit XML

IS0401Test.py, Registry.py
=> is0401: ensure a registry is advertised when checking Node mDNS

Config.py, IS0901Test.py, ReadMe.md, nmos-test.py
Following the repo's open sourcing. Just awaiting a branch renaming (now done).
=> is09: add initial files for testing of System API

IS0401Test.py
Should fix the latter part of #198
=> is04: check referential integrity of registrations

GenericTest.py
Ensures when there are multiple APIs under test (such as for the registry) that the APIs are tested in a consistent order. Also names the auto_ tests a little differently to aid disambiguation.
=> basics: ensure auto tests execute in consistent order

Config.py, TestHelper.py
=> Add config parameter to specify a preferred network interface

nmos-test.py, static/js/result_script.js, templates/result.html
Resolves #234 
I'm sure the contents of the JSON will need adding to in the future, but this is a starting point.
=> Add JSON results download capability

test_data/BCP00301/README.md
=> Clarify difference between certificate chain files and separate server certs

static/js/script.js
@mjeras Hopefully this resolves the issues you had yesterday!
=> Fix js bugs

Config.py, IS0402Test.py
And relax it a little, because, well, some systems under test do things [dreckly](https://www.google.com/search?q=dreckly).
=> Consistent WebSocket timeout

Config.py, IS0401Test.py, IS0402Test.py, IS0403Test.py, IS0502Test.py, IS05Utils.py, Registry.py
I'll be testing this tomorrow...
=> Improve IS-04-01 execution time by observing mock registry contents between sleeps

TestHelper.py
Maybe then we can close #146...
=> Report failure if redirect changed protocol from 'https'

nmos-test.py
@garethsb-sony feel free to add to this branch if you find a way to achieve the same thing on your system.
=> Exit on startup if any web server fails to start

IS0401Test.py
I made a stupid mistake which meant this gets stuck if the Node never manages to register.
=> is0401: fix stupid bug in registration waiting code

static/js/result_script.js
Minor adjustment to avoid lots of files with the same name in your downloads folder!
=> download: make file name more applicable and unique

Config.py, GenericTest.py, IS0401Test.py, IS0402Test.py, IS0501Test.py, IS05Utils.py, IS1001Test.py, ReadMe.md, Registry.py, TestHelper.py, is08/calls.py, nmos-test.py, requirements.txt, test_data/IS1001/authorization_request_data.json, test_data/IS1001/register_client_request_data.json
Inital commit of first test for registering an OAuth2 client in correspondence with RFC7591, and requesting Bearer Tokens using both the Password and Authorization Code Grant flows. 
_Ignore the blob of JSON at the start... its just acting as a referece_
=> [WIP] IS-10 - Addition of IS-10 OAuth2 Tests for registering clients and Token requests

IS0501Test.py, IS0502Test.py
This is intended to resolve #279
=> is05: test parking of senders/receivers which were subscribed

test_data/IS0401/dns_base.zone
=> is0401: fix top level DNS-SD browsing records

IS0401Test.py
Resolves #310 
I don't have a suitable implementation to test this against here, but hopefully it does the job.
I haven't resolved the checking for HTTP status codes as I wasn't sure if that was referring to an issue with a specific missing check, or just an observation that they're missing. They do appear to be missing more generally in this set of tests.
=> is0401: only test connection management for RTP transport

IS0401Test.py, Registry.py
Should resolve #297 
I've not tried this out yet but will aim to within the next couple of hours.
=> is0401: ensure we wait for the registry delete in test_21

IS0401Test.py
=> is0401: catch 'charset=utf-8' with a warning rather than fail

IS0502Test.py
=> is0502: use sampled_list to permit speed up in testing

IS0401Test.py
=> is0401: don't fail test_20 for v1.0 if v1.1 keys missing

IS0502Test.py
Minor fixes for some stray spacing in results.
=> is0502: fix large spaces in some result messages

IS0401Test.py
This extends https://github.com/AMWA-TV/nmos-testing/pull/298 to log a warning if a Node DELETEs more than just its 'node' resource when encountering a 200 on initial registration.
=> is0401: permit additional DELETE operations causing a warning

nmos-test.py, static/css/style.css, templates/result.html
A starting point for #323. Doesn't print to the results page yet, but it's included in the JSON.
I note also that the JSON doesn't indicate which API version(s) were tested which is another omission.
=> Export current configuration when saving a JSON file

IS0401Test.py
Simple fix for a casing error.
=> is0401: ensure charset warning is agnostic to casing

IS05Utils.py
=> is05: remove unnecessary check for maximum number of legs

ReadMe.md
=> Fixed typo

nmos-test.py
Resolves #269 
Unless we can come up with a better mechanism for when git metadata isn't available, this seems better than nothing.
=> Indicate a version hash when available from git metadata

IS0402Test.py
=> IS-04-02 test_21_1 Uncaught exception parsing link_header

IS0401Test.py, ReadMe.md
This is based on top of #348 to avoid merge conflicts, so will need to merge after it. Resolves #175 
It didn't feel like this warranted its own test suite, and might be more visible as part of the IS-04 Node tests.
=> Add test for BCP-002-01 grouping syntax

IS0401Test.py
Dependent upon https://github.com/AMWA-TV/nmos-testing/pull/308
=> is0401: add test referencing UUID checker

IS1001Test.py
…to account for acceptable variation (charset=utf-8).
Replaces #359.
=> IS-10-01: Check error response Content-Type using existing utility function

nmostesting/suites/IS0402Test.py
As a follow up to #371 I added a check for unexpected Node Ids as Andrew suggested.
=> Added test 22_2 for IS04: Query API WebSockets implement downgrade queries - follow up

nmostesting/suites/IS0401Test.py
=> Check RECOMMENDED registration order

nmostesting/suites/IS0401Test.py
=> Check presence of Content-Length header in POST requests

nmostesting/IS05Utils.py
=> Check for the response to PATCH /staged has the transport_params changed by the request

nmostesting/suites/IS0402Test.py
Only validate schema for the API version under test in `post_subscription`, and check Location response header for v1.3+, like `post_resource`.
Resolves #390.
=> IS0402 - fix test_22_1 for v1.1

nmostesting/IS05Utils.py
=> When a staged param was "auto", the activated value should not be "auto"

.travis.yml, Dockerfile, ReadMe.md, utilities/deploy/docker_hub
I needed to deploy an update version so I wrapped it in a docker container to deploy in my test network.
I setup automatic builds on docker hub so it always tracks master.
It would be best if there was a amwa-tv repository with this image, doing so would require the links and some commands to be updated.
=> Adding Dockerfile for deployment option

nmostesting/mocks/Registry.py
Resolves #333 
This seems the simplest of the two options and fixes both problems noted in the issue.
=> is0401: only record heartbeats if they match an existing Node

README.md, nmostesting/suites/IS1001Test.py, test_data/IS1001/register_client_request_data.json
This is a repeat of and therefore closes #354 . This is purely because the repo has changed so much that it wasn't worth the immense merge conflicts that seemed to occur.
=> [IS-10] Change result of mDNS test and request_data schema

nmostesting/mocks/Registry.py
=> registry: add missing location header in response

nmostesting/suites/IS0501Test.py
Resolves #151 
This messes the numbering up a bit, but I think that's unavoidable without confusing things by re-numbering everything else.
=> is0501: remove tests duplicated by auto section

nmostesting/suites/IS0401Test.py
=> is0401: check grain_rate present and correct

nmostesting/suites/IS0402Test.py
This should test that a v1.3+ registry correctly returns a 409 code upon a conflicting registration. We haven't got our implementation updated yet so I can't test it against that, but it certainly catches the error.
=> is0402: add a test for 409 support from v1.3+

nmostesting/suites/IS0502Test.py
=> is0502: add testing of SDP attributes against Sources/Flows

nmostesting/suites/IS0402Test.py
=> Fix recently added test_32

nmostesting/IS05Utils.py, nmostesting/suites/IS0502Test.py
This adds further testing for #342, including whether parameters are omitted from SDP files when they are present in a Flow.
=> is0502: add further transportfile tests against Sources/Flows

nmostesting/GenericTest.py, nmostesting/suites/IS0501Test.py
Adds a check for Content-Type returned by /transportfile, just checking SDP files for now.
=> is0501: check that Content-Type of transportfile is correct

nmostesting/suites/IS0701Test.py
Some very basic tests for the Events API
=> To get the ball rolling on IS-07 testing

nmostesting/suites/IS0701Test.py
As per https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/3.0.%20Event%20types.md#23-number
=> IS-07-01: Add test for consistent 'scale' values

nmostesting/suites/IS0702Test.py
Checks if websocket senders on the same device have the same:
-  **connection_uri**
-  **connection_authorization**
parameters
=> IS-07-02 test suite: Add test_03

nmostesting/suites/IS0502Test.py
@simonlo-sony This should fix the issue you noted with test_14
=> is0502: fix logic error in test_14

nmostesting/suites/IS0502Test.py, test_data/IS0502/audio.sdp, test_data/IS0502/data.sdp, test_data/IS0502/mux.sdp, test_data/IS0502/video.sdp
=> is0502: add test for staging of transport_file

nmostesting/suites/is08/calls.py
=> Check for 204

nmostesting/suites/IS0502Test.py
=> fixes #452

nmostesting/IS05Utils.py, nmostesting/suites/IS0702Test.py
=> is0702: enable senders before trying to connect to their WebSockets

nmostesting/suites/IS0501Test.py
=> is0501: check if 'auto' exists in /active resource

nmostesting/TestHelper.py, nmostesting/suites/IS0702Test.py
Also moved reusable code to get_websocket_connection_sources
=> IS-07-02: Expand test 04 to cover if WebSocket connections are kept alive when a health command is sent

nmostesting/OCSP.py
This one has existed for a while...
=> ocsp: fix path bug from restructuring of repo

nmostesting/NMOSTesting.py, nmostesting/NMOSUtils.py, nmostesting/static/js/script.js, nmostesting/templates/index.html
Work in progress
Adds the capability to specify sub-devices within an IS-08 implementation.
=> is08: permit entry of an IS-08 device instance name

nmostesting/suites/IS0402Test.py
Following a workshop discovery in our own implementation...
=> is0402: add a test to ensure registries support unicode

nmostesting/suites/IS0401Test.py
This should catch some cases where Source and Flow formats don't match up.
=> is0401: add test for Source/Flow format mismatch

nmostesting/GenericTest.py, nmostesting/Specification.py
This PR addresses several bugs in the CORS checking code. First, several case comparisons are resolved which caused some tests not to be performed. Second, a mechanism is added to pass in a set of methods/headers to check against for a given request. Finally, the error messages are improved to assist with debugging.
=> Fix errors in CORS testing

nmostesting/suites/is08/calls.py
@jasperpeeters could you see if this helps with #476? I don't have an instance to test with. Looks like one of the variables wasn't being set correctly.
=> is08: set _method variable so validation works correctly

nmostesting/suites/IS0801Test.py
This covers some errors identified by Sebastien from Embrionix/Riedel. @jasperpeeters if you get chance, as you have another IS-08 implementation it would be good to see whether this has any impact on your results.
=> is08: fix missing method calls and attributes

nmostesting/suites/IS0801Test.py
=> is0801: delete activation after checking lock

nmostesting/IS05Utils.py
Solves #500:
- Added `generate_broker_topics` for MQTT transceivers
- Added extra `KeyError` exception handling
=> Added missing mqtt parameter handling

nmostesting/suites/IS0403Test.py
Compare IS0402Test.do_dns_sd_advertisement_check
=> IS-04-03: Consistent checking and logging

nmostesting/suites/IS0401Test.py
=> IS-04-01: Add Source/Flow id to the test_24, test_24_01 messages

nmostesting/IS05Utils.py, nmostesting/suites/IS0501Test.py
Following some reports of test_41 failing to identify some incorrect SDP files, I'm taking a look for any bugs. The first issue identified appears to relate to checking for ST.2022-7 usage.
=> is0501: SDPoker fixes

utilities/run-test-suites/gsheetsImport/resultsImporter.py
=> Make absolute references to allow subsequent sorting

nmostesting/suites/IS0502Test.py
This should resolve #540 
@billt-hlit I can't easily test this at present, but it looks like a relatively obvious error. If you happen to get chance I'd appreciate it if you could confirm the fix.
=> is0502: fix error when testing a subset of is-05 resources

nmostesting/suites/IS0801Test.py, nmostesting/suites/is08/calls.py
=> /props endpoints became /properties before v1.0

Dockerfile, nmostesting/NMOSTesting.py, nmostesting/suites/IS0501Test.py
=> sdpoker: update minimum version to v0.2.0

nmostesting/Config.py, nmostesting/NMOSTesting.py, nmostesting/suites/BCP00301Test.py
This facilitates running testssl.sh on windows using WSL and should work as before on other platforms
=> explicitly run testssl.sh in bash

nmostesting/suites/IS0802Test.py
This should fix the issue created by using a set to store dicts.
=> is0802: fix incorrect use of set with dicts

nmostesting/suites/IS0402Test.py
"A 501 HTTP status code MUST be returned where pagination is attempted against a Query API which does not implement it."
As per https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.3/docs/2.5._APIs_-_Query_Parameters.html#pagination
=> IS-04-02: Require 501 response to explicit paging request if not supported

nmostesting/suites/IS0801Test.py
Been experimenting with IS-08 Input and Output caps and found some problems.
Hopefully this fixes #591.
=> IS-08-01: Fix broken tests

nmostesting/suites/IS0801Test.py, nmostesting/suites/IS0802Test.py, nmostesting/suites/is08/action.py, nmostesting/suites/is08/activation.py, nmostesting/suites/is08/active.py, nmostesting/suites/is08/calls.py, nmostesting/suites/is08/inputs.py, nmostesting/suites/is08/outputs.py
And some editorial tweak, but mainly see `Active.getAcceptableActionsForOutput`!!
Fixes #590.
=> Do better at identifying acceptable actions based on output and input constraints

nmostesting/Config.py, nmostesting/GenericTest.py, nmostesting/NMOSTesting.py, nmostesting/TestHelper.py, nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0502Test.py
Beginnings of BCP-004-01 Receiver Capabilities test cases to resolve #586
=> BCP-004-01: Receiver caps

nmostesting/suites/IS0401Test.py
=> is0401: fix case comparison issue in test_20

nmostesting/Config.py
https://github.com/AMWA-TV/nmos-parameter-registers/commit/85c966f7ead5d0a2c8a6c5192ec6ed372126b442
=> Capabilities register has been merged to main

.deploy/Makefile, .deploy/make-container.sh, .deploy/upload-container.sh, .github/workflows/deploy.yml
Following issues with the amd64 Docker image, this attempts to correct the issue and build for multi-arch.
Resolves #579
=> Update GH Actions deploy workflow to build multi-arch

nmostesting/IS05Utils.py, nmostesting/suites/IS0501Test.py
Resolves #624, two different exception reporting bugs.
=> [IS-05-01] Exception fixes

.github/workflows/lint.yml, nmos-test.py
After moving to GitHub actions we weren't running flake8.
=> Fix flake8

.render/_data/README.md
Support dynamic menus for rendering
=> Add _data dir

nmostesting/suites/IS0502Test.py
=> [IS-05-02] Fix FAIL formatting

.render/_data/README.md, testingfacade/APIs/AnswerAPI.raml, testingfacade/APIs/QuestionAPI.raml
Incorrect indentation caused render problem
=> Fix indentation

nmostesting/ControllerTest.py
=> Fix whitespace

nmostesting/mocks/Node.py, nmostesting/suites/IS0503Test.py
Added parsing of SDP files in PATCH of /staged endpoint in mock Node.
This should fix issue #647
=> Parsing of SDP files in mock Node

nmostesting/mocks/Registry.py
Fixed `_create_and_queue_data_grains` `KeyError` bug in Registry.py. Now iterates over available subscriptions for resource rather than assuming resource always has single subscription.
This resolves #658
=> Fixed KeyError bug in Registry.py

nmostesting/suites/IS0401Test.py
=> [IS-04-01] Fix uncaught ZeroDivisionError

README.md, docs/2.2. Usage - Testing BCP-003-01 TLS.md, docs/2.3. Usage - Testing IS-10 Authorization.md
Motivated by adding BCP-004-01
=> Rework list of test suites

nmostesting/suites/BCP00301Test.py, nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0702Test.py
Broken since:
* https://github.com/AMWA-TV/is-04/pull/175
* https://github.com/AMWA-TV/is-07/pull/77
* https://github.com/AMWA-TV/bcp-002-01/commit/8e256073e136cbec36748ac0c11d546536ba7dbc
* https://github.com/AMWA-TV/bcp-003-01/pull/4
* https://github.com/AMWA-TV/bcp-004-01/pull/27
=> Fix doc links since numbering removed from filenames

nmostesting/TestHelper.py, nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0402Test.py
=> Better check for whether a host is an IP address

docs/2.2. Usage - Testing BCP-003-01 TLS.md
This links to the dir rather than the readme directly
=> Update 2.2. Usage - Testing BCP-003-01 TLS.md

test_data/BCP00301/README.md, test_data/core/dns_base.zone
Add CRL and OCSP's DNS address records to the DNS zone file
=> Update zone file to include crl and ocsp settings

test_data/BCP00301/ca/generateCerts
@lo-simon please would you check this makes sense to you as well?
=> [JT-NM Tested][BCP-003-01] Export chain as PFX file as well as PEM format

nmostesting/Config.py
=> Fix default MULTICAST_STREAM_TARGET

nmostesting/suites/IS0502Test.py
=> Fix ts-refclk parsing

nmostesting/suites/IS0502Test.py
Also warn if RTP Receivers are missing optional 'caps.media_types'.
=> [BCP-006-01] Manual testing is required if we cannot generate SDP data for any of a Receiver's supported media types

nmostesting/GenericTest.py, nmostesting/TestHelper.py
=> Fix IS-04 auto_node_17 (Missing Authorization_header) test

nmostesting/static/css/style.css, nmostesting/static/js/script.js
=> Remove stale alerts on starting a new run

nmostesting/IS05Utils.py, nmostesting/suites/IS0501Test.py, nmostesting/suites/IS0502Test.py
Quick, dirty, fix so that `IS0501Test.test_09_01` reports a 404 from the `/transportfile` endpoint like `test_41` and `test_42` already do
Resolves #503, sort of.
=> [IS-05-01] Fix test_09

Dockerfile, nmostesting/NMOSTesting.py, nmostesting/suites/IS0501Test.py
Merge only after AMWA-TV/sdpoker#21 is merged and v0.3.0 released
=> sdpoker: update minimum version to v0.3.0

docs/2.8. Usage - Testing Controllers.md, nmostesting/Config.py, nmostesting/ControllerTest.py, testingfacade/APIs/schemas/question-schema.json, testingfacade/templates/index.html
=> Make Controller Testing Timeout Configurable

.github/workflows/deploy.yml
=> Include spec repos in docker image

nmostesting/NMOSUtils.py, nmostesting/suites/IS0502Test.py, nmostesting/suites/IS0702Test.py, nmostesting/suites/IS0802Test.py
Cherry-picked from @N-Nagorny #806.
=> Add common method to test Device control advertisements

nmostesting/NMOSTesting.py
It only handled version specifiers beginning with `>` before!!
=> Better parsing of requirements.txt lines

nmostesting/MS05Utils.py, nmostesting/suites/IS1401Test.py
Addition of two tests:
* Node under test handles incorrect datatypes in restore
* Node under test handles constraint violations
=> IS-14: Additional tests ensuring datatype and constraint consistency
