AMWA-TV/nmos-testing

IS0401Test.py, Node.py, nmos-test.py, test_data/IS0401/audio.sdp, test_data/IS0401/data.sdp, test_data/IS0401/mux.sdp, test_data/IS0401/video.sdp
I've squashed three paper tests into two code tests to make it slightly easier. I'd appreciate this being run against at least one other implementation before it's merged in as there's a good chance some of the SDP file contents will need to be parameterised in order to get them accepted in all cases (for example changing source IPs to something in the range under test).
Resolves https://github.com/bbc/nmos-testing/issues/29
=> Add IS-04 Node Receiver target tests

Config.py, IS0401Test.py, nmos-test.py
This is a work in progress. Currently it adds a way to disable mDNS advertisements and marks the related tests as manual. Eventually it will include the ability to keep performing some of the tests by using a Query API configured in Config.py and making GET requests to it in the same way that the Riedel test suite used to.
=> Add ability to disable mDNS advertisements via config parameter

nmos-test.py
Since the index page doesn't show the test suite id like "IS-04-01" to the user, only the human-friendly name like "IS-04 Node API", shall we do the same in the results page?
=> Show the human-friendly name like "IS-04 Node API" in results page

IS0402Test.py
Posting a resource without the parent resource should result in a 400.
Currently only a Device without parent Node is tested. 
Question: Do we want to test all other possible resources additionally?
=> Adding test for posting resource without parent

IS0401Test.py
… and unadvertise the first registry so that the Node won't retry this one even if its "discovered list" is empty, triggering it to perform a re-query. Fixes #108.
=> Fix repeated multi-reg testing

Config.py, IS0501Test.py, NMOSUtils.py
Resolves #84 
@billt-hlit could you see if this resolves your issue? You'll need to configure an appropriate limit in Config.py.
I've applied the limit to the obvious slow tests in IS0501, but I'm sure there are others elsewhere. If you're immediately aware of any others that cause a pain point please let me know and I'll include them here, otherwise we'll catch them later.
=> Add config option to restrict number of iterations for some tests

GenericTest.py, IS0401Test.py, IS0402Test.py, IS0501Test.py, IS0502Test.py, TestResult.py, static/css/style.css, templates/result.html
When a test cannot proceed because of a temporary condition (e.g. no resources of a particular type in a Registry) it seems better to clearly flag that as needing manual intervention (e.g. register a node with the appropriate resources), rather than as N/A.
Maybe there's a confusion in the meaning of "N/A"... "Not Applicable" or "Not Available". The CSS class is "notavailable", but most uses are like ``test.NA("This test does not apply to v1.0")``.
I didn't apply the same to the Node API tests, because a Node could reasonably never have resources of a particular type.
Other initial commit is a simple rename because the "Not Implemented" status wasn't rendering correctly in my web browser.
=> Clearer flagging of tests that don't proceed

IS0402Test.py, TestHelper.py
Adding the last missing schema validation for the Event messages received via the websocket subscriptions.
As the schema for the event messages is a slightly different case (not reachable via the `QueryAPI.raml`) in comparison to the other schemas, I have to load the schema and validate manually at the moment.
Currently only SYNC messages are validated, but as they have both (`pre` and `post`) messages filled, I think this might be enough and there is no need to validate the messages for MODIFIED, ADD and DELETED as well. Thoughts?
=> Add JsonValidation for event messages

Config.py, ReadMe.md
Small modification to the `Readme.md`:
Added a hint to update the query_api_host / ip  and port to sensible values, once the `ENABLE_MDNS` flag is set to False.
If the query api runs on a different machine, some of the tests will unavoidably fail if those parameters are not set.
=> Added hint to update QueryAPIHost / IP in readme if mdns is disabled

IS0402Test.py, NMOSUtils.py
We're attempting to convert an internal unit test suite into API-based tests for the 'paged' trait.
This is the beginning:
1. Check all required response headers are present
2. Check the most recently POSTed resource is at the top of the initial page of results
3. Check paging.limit restricts the response to the specified number of results
More to come...
=> Tests of Query API cursor-based pagination

Config.py, DNS.py, IS0401Test.py, IS0402Test.py, IS0403Test.py, ReadMe.md, nmos-test.py, requirements.txt, setup.py, templates/index.html, test_data/IS0401/dns.zone, test_data/IS0401/dns_base.zone, test_data/IS0401/dns_records.zone
Work in progress. This is intended to add support for unicast discovery testing. At present I'm unable to test it fully on Linux as the default port is already in use. Assuming it can be made to work it would provide a much better testing method for shared networks.
Note that the DNS server implementation itself has been tested and found to work when running on a non-standard port.
=> Add support for testing discovery using unicast DNS

GenericTest.py, IS0402Test.py, nmos-test.py
This PR provides a new exception type which can be thrown during a given test set's `__init__` call. In its first usage it checks that the Registration and Query API versions under test match, and the tests are very heavily dependent on this being the case.
=> Abort testing if the selected configuration is invalid

GenericTest.py
...or there was an uncaught exception.
I had a look at using ``functools.wraps`` on the ``invalid`` decorator to solve the first case, but I couldn't see how to access the function object and get its ``__name__`` using ``inspect`` within the ``Test`` constructor.
And we already had the information and the option to pass it in, so this is an easy fix!
=> Add the correct test name when @test_depends has been used

IS0402Test.py, ReadMe.md, TestResult.py, nmos-test.py, requirements.txt
Will resolve #43 
This is just a bit of refactoring with the aim to permit command line operation triggered by automated testing jobs.
I'd appreciate thoughts on whether the unit under test should be passed in via command line argument or use of the existing Config file. Equally, if passing things in via the command line should it be possible to override Config.py values via this method?
Also, what format would the test results be most useful in? I'm intending that the exit code reflects the worst test result encountered in the pass, but the detail of failures could be formatted however is most useful.
=> Enable non-interactive testing

IS0402Test.py
We have a bug causing test_28 to fail. When this happens, because the test leaves some data in the registry and test_30 assumes that the registry is capable of passing test_28, test_30 also fails. If test_30 is run in isolation it works fine.
This patch modifies the cleanup step at the start of test_30 to avoid the dependency on the behaviour of test_28.
=> is0402: modify cleanup step at the start of test_30

GenericTest.py
I'd consider this to be a bug according to the trailing slash policy. Unfortunately as an artefact of the way RAML is specified the top level resource is defined by a slash, which was causing the likes of GET /x-nmos/node/version to be tested with a slash at the end. This corrects that behaviour in order to bring it into line with the general policy.
=> Strip trailing slash when testing API base resources

IS0402Test.py
...to "permit Senders without attached Flows to model a Device before internal routing has been performed"
See https://github.com/AMWA-TV/nmos-discovery-registration/commit/a95025eea191d7478b21f72b6b8a2421ba8c0a36.
Flip-side of #114.
=> IS0402 - Test case for v1.1+, which introduced null for flow_id

GenericTest.py, IS0401Test.py, Registry.py
Replaces #168.
Implements https://github.com/amwa-tv/nmos-discovery-registration/blob/v1.2.1/docs/2.2.%20APIs%20-%20Client%20Side%20Implementation%20Notes.md#empty-request-bodies
=> Check for empty request bodies on POST /health/nodes/{nodeId}

.gitignore, BCP00301Test.py, Config.py, GenericTest.py, ReadMe.md, nmos-test.py, static/js/script.js, testssl/README.md
A new test set as testssl.sh takes quite a while to run tests, so we won't want to run them all the time. Initially covers TLS versions and cipher suites, but will be expanded. Requires a download of testssl.sh which I'll add further documentation for before review.
=> Add initial support for testing BCP-003-01 TLS support

BCP00301Test.py
@garethsb-sony this may work better. I should have just used split()'s defaults in the first place.
=> bcp00301: fix parsing when spaces used in string separation

BCP00301Test.py, GenericTest.py, IS0401Test.py, IS0402Test.py, IS0403Test.py, IS0501Test.py, IS0502Test.py, ReadMe.md, TestResult.py
Getting rid of the duplicate descriptions of the test cases seems like a win.
The implementation is a little fragile, mostly around interaction with `@test_depends`, but @KevinTao-Sony is readying a PR to get rid of all uses of that (only in `IS0402Test`).
=> De-duplicate all the test case descriptions

static/css/style.css, static/js/result_script.js, static/js/script.js, templates/index.html, templates/result.html
Disable 'runbtn' when no tests are selected, and use 'onsubmit' rather than 'onclick' so that the button can actually be disabled visually when 'Executing tests...' (hopefully a better fix cf. c826b1c094c932ea863a12784ff803e672732217)
=> Tweaks to avoid frustration of hitting 'Run' when there are no tests selected

Config.py, ReadMe.md, Specification.py, nmos-test.py
This doesn't work yet, but in looking at BCP003-02 RAML I added this test set, so thought I'd leave it here until it's ready to merge.
=> Add boilerplate for BCP003-02 API testing

GenericTest.py, TestHelper.py, test_data/core/error.json
This goes at least part of the way to resolving https://github.com/AMWA-TV/nmos-testing/issues/173
It's hard to test every error code in an automated fashion, and we do already check the schema returned by registries for 400s, but this adds something basic to test out every API implementation.
=> Add invalid path test for error JSON validation

BCP00301Test.py, IS0401Test.py, IS0402Test.py, ReadMe.md, nmos-test.py, static/js/script.js, templates/index.html
This adds a check for the HSTS header. It also performs some vulnerability testing via testssl, however as this isn't strictly part of BCP003-01 it's questionable whether it belongs here.
I may add some further checks on certificate verification and OCSP stapling before completing this one.
=> Add further BCP003-01 testing

ReadMe.md, nmos-test.py
Following a request from Felix at CBC, I've added some extra command line arguments (and modified one) to allow listing and describing of suites and tests.
=> Add further command line arguments to list and describe tests/suites

IS0402Test.py
E.g. when resource registrations from prior tests expire during test_31
=> Fix uncaught KeyError: 'post' and the like from WebSocket tests

Registry.py
This should resolve #179 unless there are multiple Nodes interacting with the registry at the same time. I could do something a little more complex to ensure the correct response codes are sent in these cases too, but I'm not sure if it's really necessary.
=> Resolve 200 code sticking after IS-04 test_21

IS0801Test.py, IS0802Test.py
This should resolve #205, but I don't have an IS-08 implementation in order to confirm 100%.
I haven't added any further testing of the affected endpoint, but this should prevent failures being recorded incorrectly.
=> is08: prevent auto testing of /map/active/{outputId}

DNS.py, IS0401Test.py, Node.py, TestHelper.py
Add utility function to get default ip, using default gateway if found, attempting fallback otherwise.
Resolves #216.
Can probably still throw KeyError etc. if no interfaces found, or the fallback interface doesn't have an IPv4 address, but that's no worse than things were already...
=> Add utility function to get default ip

IS0501Test.py, ReadMe.md
I'd suggest this may need testing against a few implementations before merging. I'm also not certain how well it will handle non-2110 SDP files, but that may be something we need to contribute back to sdpoker for in order to have a suitable command line argument.
=> is0501: add testing of SDP files by calling out to sdpoker

ReadMe.md
Very minor, just an additional Readme entry for SDPoker as an external dependency.
=> readme: add reference to sdpoker in external dependencies

BCP00301Test.py, BCP00302Test.py, CRL.py, IS0801Test.py, IS0802Test.py, IS0901Test.py, is08/__init__.py, is08/action.py, is08/activation.py, is08/active.py, is08/calls.py, is08/helperTools.py, is08/inputs.py, is08/io.py, is08/outputs.py, is08/testConfig.py
As-per https://github.com/AMWA-TV/nmos-testing/pull/221#issuecomment-490082820
I've changed the header for files which were obviously added since we moved to AMWA-TV, but can add to others if needed.
=> Update copyright headers for recently added files

IS0401Test.py
Provides a better test result for the case where no registrations were made with the mock registry.
=> is0401: don't pass the ref integrity check if nothing registered

IS0401Test.py
Resolves #198.
Perhaps the `OPTIONAL` result needs an explanatory paragraph added in the NMOS wiki? There isn't much of a rationale in https://github.com/AMWA-TV/nmos-discovery-registration/commit/0f4e04dc68667ed8fa6aba57e518e6589e022f5b.
=> Check each Device's 'senders' and 'receivers' arrays

IS0401Test.py, Registry.py, test_data/IS0401/dns_records.zone
Another one that I think may require some feedback. I'm attempting to add a test to ensure that Nodes only register with registries which have suitable TXT records.
The trouble is that when a Node fails this test, lots of other tests fail because the Node has registered with the invalid first registry. As such it could make a Node look far less compliant with the spec than it really is. Potential resolutions include re-ordering the prereqs tests so that the invalid registry test happens after the others (however this will incur an additional 'DNS_SD_ADVERT_TIMEOUT' wait period). An alternative would be to add a further IS-04 Node test suite which covers some more time consuming tests. Any thoughts?
Notes:
* Untested with unicast so far
* Will require an exception for v1.0 as this didn't …
=> is0401: ensure Nodes correctly interpret registry TXT records

test_data/BCP00301/README.md, test_data/BCP00301/ca/generateCA, test_data/BCP00301/ca/generateCerts, test_data/BCP00301/ca/generateDefaultCerts, test_data/BCP00301/ca/openssl.cnf.intermediate
This shouldn't make any difference to the test suite itself (or the existing certificates), but makes the scripts a little more flexible to support generation of a CA/certs for an alternative domain name.
Ports and similar for the CRL/OCSP server remain hard-coded for now.
=> Modify CA scripts to support modified domain names

IS0401Test.py, test_data/IS0401/dns_records.zone
Untested as yet. This is an attempt to extend the failover tests to identify any Nodes which have a connection/request timeout figure set to a default which is likely to be far longer than required in this situation.
The second to last registry in the advertised list doesn't exist and uses an unroutable IP address intended for documentation. The test should ensure that a connection to this address times out within one heartbeat interval, and the Node then proceeds to the next best registry, successfully heartbeating with it.
This builds upon the changes in https://github.com/AMWA-TV/nmos-testing/pull/232
=> is0401: add tests for handling of timeouts from Registration APIs

CRL.py, Node.py, Registry.py, nmos-test.py, test_data/IS0401/dns_records.zone
… in order to fix failing IS0401Test.test_13 due to the additional Registry bumping the port number of sender_app (and crl_app)
=> Rework assignment of ports to the various Flask apps

testssl/README.md
Having set this up on a new host I realised my version of testssl was patched to resolve an OCSP issue which causes failures for all tests using that check mechanism.
=> testssl: update version requirement to include bug fix for OCSP

.gitignore, OCSP.py, nmos-test.py
This relies upon openssl to do a good job of escaping the file input to avoid a remote code execution issue. Otherwise it'll require some pre-parsing of the input.
=> Add support for an OCSP server

IS0402Test.py, nmos-test.py
`ENABLE_DNS_SD` is only intended to handle advertisements made by the test suite, not browsing, so we only check `DNS_SD_MODE` to decide whether to disable `IS0402Test.test_01/_02`.
=> IS-04-02 Don't check for mDNS advertisements in 'unicast' mode

IS0401Test.py
… not an IP address
Also:
* Check Node 'href' has a corresponding entry in 'api.endpoints'
* Check specified hostname and port (with current scheme) have a corresponding entry in 'api.endpoints'
One more step towards finishing #146.
=> Check all the Node's resources' "https" endpoints/URLs have a hostname

IS0402Test.py
Includes improved checks for:
* Location header in Registration API response to POST /resource
* Link header in Query API paged response
* 'ws_href' in Query API POST /subscriptions response
=> Check all the Registry's "https" URLs in response headers have a hostname

IS0401Test.py, Registry.py
When testing a Node which didn't observe the TXT records the previous fix to avoid waiting for the full `DNS_SD_ADVERT_TIMEOUT` wasn't sufficient. This approach should cover it slightly better.
=> is0401: escape timeout if registration with invalid reg detected

BCP00301Test.py, GenericTest.py, IS0401Test.py, IS0402Test.py, IS0502Test.py, IS0802Test.py, nmos-test.py
I'd prefer to catch a more specific exception, but this seems to be the only straightforward way around the issue of simplejson vs. json at present.
=> json: handle potential for different exception names. Resolves #261

Config.py
Attempting to address a query which resulted from not having spotted the readme file after cloning the repo.
=> config: add a prominent note about the ReadMe file

Registry.py
Following a report of an issue encountered by an implementation, this PR adds support for the base GET against a Registration API which the spec indicates will always be present.
=> registry: add support for base path GET as-per API docs

Registry.py
I had implemented the 'primary' path, but failed to adhere to the server requirements in https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/2.0.%20APIs.md#get-and-head-requests. Disabling `strict_slashes` provides one way around this.
I've also added an explicit 404 code for when the registry is disabled, which seems slightly more applicable than a 5xx in this case.
=> registry: fix trailing slash policy adherence

BCP00301Test.py
This adds a test for the chain of trust for certificates. This is technically already covered by test_07, but it seems sensible to have something a little more explicit.
=> bcp003: add an explicit test for trust chains in certificates

BCP00301Test.py
This is in preparation for a change to the required cipher suites which will make support for RSA certs mandatory instead.
=> bcp003: change ecdsa check to warning rather than fail

IS0401Test.py
Added test for v1.3+: no mdns announcement should be made at all in the presence of a registry
Solves #277
=> Added check for no mdns announcement for v1.3+ in the presence of a reg

Config.py, GenericTest.py, ReadMe.md
It was pointed out to me by Miroslav that if you need to restart your Node in order to test unicast discovery, simply increasing `DNS_SD_ADVERT_TIMEOUT` can have some unintended consequences. If your Node is mid-reboot when the testing starts the 'auto' tests will indicate a fail as the waiting only happens after these have executed. This PR adds a wait period ahead of any tests running, but after the `set_up_tests` method which prepares the DNS server.
=> Add config to delay testing after selecting what to run

is08/calls.py, is08/outputs.py
This resolves an issue encountered in test_01 where the JSON comparison would fail because the source_id in the mock IO resource had double quotes around it.
=> is08: fix error with double quotes appearing around source_id

BCP00301Test.py
This should only be merged once https://github.com/AMWA-TV/nmos-api-security/pull/38 has become part of the spec.
=> bcp00301: update mandatory tls1.2 ciphers

IS0502Test.py
Whilst modifying another part of the IS-05-02 tests I spotted this which didn't look quite right. I'll try it out shortly to see how this change behaves.
(One commit only, it's just based on top of other changes).
=> is0502: set unicast tests to use a unicast address

IS0401Test.py
We noticed that for some Nodes it's possible that the data held by the mock registry wouldn't match their Node API once we hit `test_04` and similar. The only difference was the 'version' key. Given that the mock registry doesn't accept updates to registrations later in the process this may cause a failure when everything was actually fine.
This PR aims to change the time at which we fetch data from the Node API in order to better match up with when registrations happen. It also changes the test results to produce a warning rather than a failure if the only difference between registered resources and the Node API is the version attribute.
This is currently untested, but I'll be running it against a few Nodes shortly.
=> is0401: capture Node API resources at the same time as registrations

IS0401Test.py, IS0402Test.py, IS0403Test.py
Resolves #314 
I stopped short of patching zeroconf given it does just handle these values. The only edge case may be  a TXT record with an empty value which could evaluate to `False`, but I'm not sure it's worth the potential for the patch to fail in the future to cover that case.
=> is0401: fix failure in api_auth TXT record checks

IS0401Test.py, Registry.py
I haven't tested this out yet but will be doing so early next week.
Due to the fact we don't want the tests to take any longer than necessary, some tests run at the same time as each other. At present if a Node fails `test_01_01` or `test_02_01` it may be unfairly penalised in other tests (such as `test_03`, `test_04` etc). This change intends to check both the primary registry and invalid registry when performing these basic registration tests so that this discovery failure isn't recorded as a failure in multiple places.
=> is0401: improve other results if Node fails to pick correct registry

IS0801Test.py, is08/activation.py
Sébastien from Embrionix noted that the `checkReject` method referencing in IS-08 `test_13` was missing. @simonrankine suggested the following as a fix, but this is currently untested. If anyone who has an IS-08 implementation can review and verify it that would be appreciated.
=> is0801: add missing method for test_13

ReadMe.md
Adds a missing dependency for Linux systems. Thanks to John at Imagine for spotting.
=> readme: add missing libssl-dev external dependency

nmos-test.py
This commit should make it a little easier to debug some of the IS-04 mock registry tests. It should ensure that the mock servers' port numbers get logged each time a request comes in.
=> http: log web server port number for each request

nmos-test.py
This makes the request logging look as intended.
I haven't noted colorama in requirements.txt because it's only necessary on Windows.
=> Make ANSI escape character sequences (for producing coloured terminal text) work under Windows

nmos-test.py
When the testing tool is deployed at events we occasionally find it hangs, likely due to an oversized timeout. It is relatively hard to tell when this has happened unless you are the one that triggered the test run that caused it. This debug print is intended to make it more obvious that the testing tool has indeed hung given the length of time a test run is taking.
=> Log time since a test run began if another one is attempted

IS0401Test.py
Whilst unlikely, if one of a Node's resources was updated during the registry failover tests, it could quite correctly issue a heartbeat followed by a POST to /resource. It would be hard to detect this accurately if the updated resource was the 'node' but this should handle the case where the issue is with any other sub-resource.
=> is0401: don't fail test_16 if a resource update happens during test

IS0401Test.py
… due to processing error responses as if they were valid responses.
Easy to test what happens before/after this by running IS-04-01 Test on a Connection API!
=> IS-04-01: Check response status_code to avoid uncaught exceptions

CRL.py, Config.py, DNS.py, Node.py, OCSP.py, Registry.py, nmos-test.py, test_data/IS0401/dns_records.zone
It would be useful to be able to run the tool as multiple instances on the same host. To do this I need to offset the port ranges used. Use of `ENABLE_DNS_SD` when running multiple instances won't be possible, but it'll help to test things other than discovery.
=> ports: allow base port number to be configured

test_data/IS0401/dns_records.zone
Follow-up to #299, to make the zone file easier to read and maintain. Not intended to change the DNS records that are created in any way.
=> Zone file template

is08/activation.py, is08/calls.py
This ensures that '.json()' isn't called for cases with no content in their responses.
=> is08: fix test for 204 no content response

_layouts/default.html
Caused a 404 on "OVERVIEW" in the GitHub pages menu as was pointing to non-existent overview in this repo. Now points to nmos technical overview.
=> Fix link to overview in _layouts/default.html

GenericTest.py, IS0501Test.py
Leaving this one until after next week's event to avoid being unfair to pre-tested implementations.
This adds schema checking to the 405 responses from the IS-05 API.
=> is0501: check error schema for test_34/35

IS0501Test.py, IS0502Test.py, IS05Utils.py
This is intended to complete #152, but is as yet untested on a WebSocket implementation.
The hope is that for Senders where the 'connection_uri' is not changeable, this will be advertised via a single entry in an enum and will be staged/activated to the same value it was previously. For Receivers a fake 'connection_uri' is generated using the current IP and port of the testing tool.
=> is05: add testing for WebSocket parameter changes

TestHelper.py, nmos-test.py
Resolves #363 and resolves #194
In order to check the internal dependencies a small number of mappings are required between package and importable names.
=> deps: check internal and external dependencies on startup

Config.py, DNS.py, GenericTest.py, IS0401Test.py
Adds a watcher to the DNS server so that tests can proceed immediately upon a relevant query being received. This should remove the need for 'TEST_START_DELAY'.
Relates to #252
=> dns: add watcher to DNS server to notify upon queries

IS0501Test.py, IS05Utils.py
This is a starting point for #342 
In the absence of an obvious Python SDP parser (and without wanting to bring in all that comes with https://github.com/bbc/nmos-device-connection-management-ri/tree/master/nmosconnection) I've stuck to regexes for now, but we'll see how that goes.
At present this doesn't take account of the fact SDP files may be unavailable for disabled Senders.
=> is0501: check SDP files change in line with transport_params

GenericTest.py, nmos-test.py
Resolves #143 
This should avoid cases where the full set of results will come back as fails after a long wait.
Also includes a minor improvement to the message returned when a port is missing from the web form.
=> Check presence of API under test before performing full test suite

IS05Utils.py
Suggesting this regex improvement regarding #375 .
Old: `c=IN IP[4,6] (\S[^/]*)(/[0-9]+)?`
New: `c=IN IP[4,6] ([^/\r\n]*)(?:/[0-9]+){0,2}`
Couple comments:
- Regex for Ipv4 _and_ Ipv6 can be as much as complicated as we want,.. but as we only want to compare the values, this very relaxed RE should do the job
- Not sure what the reason for the `\S` was in the initial RE
- `<TTL>` and `<number of addresses>` _may_ follow (or _must_ for multicast), but are not of interest, therefore non-capturing
=> is05-sdp-check: Regex improvement

nmos-test.py, static/js/script.js
Requested by @bgilmer77 
This makes it possible to see test descriptions before picking them. The alternative would be to finish https://github.com/AMWA-TV/nmos-testing/issues/24, but there's only so much description you can get into 31 characters. I suspect that issue may become less relevant as a result and existing names in methods could be removed.
=> ui: display descriptions alongside test names in selection box

nmos-test.py
Also mark ignored test cases as disabled in the JSON output (similarly to how they're marked as skipped in the JUnit XML output)
=> Honour which test cases have been --ignore'd in working out the exit code

IS0401Test.py, IS0402Test.py
As identified in #372, we should probably add schema validation using `check_response` after all instances of `do_request`, for both 2xx and 4xx responses.
This PR focuses on the success responses to those requests that aren't already tested in the "auto" tests (most GET requests will have been, DELETE gets a 204 empty response, but POST, PATCH and PUT responses need checking). That means:
**IS-04-02**
* POST /subscriptions (`post_subscription`)
* POST /resource (`post_resource`)
* POST /health/nodes/{nodeId} (`test_30`)
**IS-04-01**
* PUT /receivers/{receiverId}/target (`do_receiver_put`)
**IS-05-01**
* PATCH /single/{resourceType}/{resourceId}/staged (in/after `checkCleanRequestJSON`)
=> Check more API responses for schema validation errors

README.md, nmostesting/CRL.py, nmostesting/DNS.py, nmostesting/GenericTest.py, nmostesting/IS05Utils.py, nmostesting/NMOSTesting.py, nmostesting/NMOSUtils.py, nmostesting/OCSP.py, nmostesting/Specification.py, nmostesting/TestHelper.py, nmostesting/suites/BCP00301Test.py, nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0402Test.py, nmostesting/suites/IS0403Test.py, nmostesting/suites/IS0501Test.py, nmostesting/suites/IS0502Test.py, nmostesting/suites/IS0801Test.py, nmostesting/suites/IS0802Test.py, nmostesting/suites/IS1001Test.py, requirements.txt
The top half of changes are linting / tidying changes, but the bottom half adds a route (`/api`) that allows the sending of a JSON body that contains the same parameters that the command line consumes, and returns a `json` or `xml` output, depending on the presence of a `format=json/xml` query parameter.
=> Add API route for automated testing

nmostesting/GenericTest.py, nmostesting/suites/IS0401Test.py
Addresses part of #340 
I can't find a reference which indicates whether Accept is mandatory, but given we default to returning application/json anyway it's probably not an issue if it's omitted from a request.
=> is0401: add check for Accept header

nmostesting/IS05Utils.py
Not sure why I didn't include this originally, but this adds an extra check for the multicast IP used in a source-filter.
=> is0501: add extra source-filter test for matching multicast IP

nmostesting/suites/IS0502Test.py
Needs checking. I have a few test cases for the `channel_order` function itself but wasn't sure where to put those!
```python
TESTS = [
["SMPTE2110.(ST)", [{ "symbol": "L" }, { "symbol": "R" }]],
["SMPTE2110.(DM)", [{ "symbol": "M1" }, { "symbol": "M2"}]],
["SMPTE2110.(51,ST)", [{ "symbol": "L" }, { "symbol": "R" }, { "symbol": "C" }, { "symbol": "LFE" }, { "symbol": "Ls" }, { "symbol": "Rs" }, { "symbol": "L" }, { "symbol": "R" }]],
["SMPTE2110.(M,M,M,M,ST,U02)", [{ "symbol": "M1" }, { "symbol": "M1" }, { "symbol": "M1" }, { "symbol": "M1" }, { "symbol": "L" }, { "symbol": "R" }, { "symbol": "C" }, { "symbol": "LFE" }]]
]
for T in TESTS:
print(T[0] == channel_order(T[1]))
```
=> Add a test for the SMPTE ST 2110-30:2017 'channel-order' format-specific parameter

nmostesting/Config.py
Now that the tests will proceed without waiting after a successful query/request, it seems safe to increase the default DNS-SD advert timeout. This should make testing unicast discovery a little more likely to succeed with the defaults.
=> config: update discovery default to ease unicast testing

nmostesting/suites/IS0401Test.py
Adds a test which emits warnings only if expected 'caps' are missing for different types of Receivers.
=> is0401: add a test for the presence of Receiver caps

nmostesting/suites/IS0502Test.py
This adds a further SDP check to ensure that ts-refclk and IS-04 Source clocks match up.
=> is0502: check SDP clocks match IS-04 Sources

nmostesting/IS04Utils.py, nmostesting/IS07Utils.py, nmostesting/NMOSTesting.py, nmostesting/suites/IS0702Test.py, nmostesting/suites/IS0703Test.py
This creates a new test suite IS-07-02 which will be handling all of the integration tests between IS-07, IS-04 and IS-05. Transport tests will be added here as well.
Currently just 2 tests have been added:
- test 01 - checks the ext parameters exist (ext_is_07_source_id, ext_is_07_rest_api_url)
- test 02 - checks if the sources have a corresponding IS-05 sender and if not return a warning
=> IS-07-02: Add initial test suite for integration tests between IS-07, IS-04 and IS-05

nmostesting/suites/BCP00301Test.py
Looks like I missed this file when re-formatting things a month or two back.
=> bcp00301: remove legacy method naming

nmostesting/suites/IS0701Test.py
This PR adds a exception handler for a type error in test_06_02 of IS-07-01
=> IS-07: catch type-error exeception in test_06_02 (string payload type)

nmostesting/TestHelper.py, nmostesting/suites/IS0702Test.py
Checks if WebSocket connections get closed after the timeout period specified by the spec but also that the connections are not closed too early.
If senders are not enabled using "master_enable" then a WARNING is returned.
=> IS-07-02: Add test 04

nmostesting/suites/IS0401Test.py
Resolves #421 
This is such a minor check I thought it best to include it in the existing relevant test rather than writing a whole new one.
=> is0401: add a check to ensure interface_bindings not empty

nmostesting/IS05Utils.py, nmostesting/suites/IS0501Test.py
Resolves #434
This ensures that 'master_enable' is set to true for the set of tests which aim to examine resultant SDP files for RTP senders.
=> is0501: ensure senders are enabled before testing SDP files

Dockerfile, docs/1.1. Installation - Local.md, docs/2.4. Usage - Testing of SDP Files.md
This updates the build and instructions to reference the patched version of SDPoker until a new official release is available via NPM.
=> Adjust build and docs to use fork of SDPoker

nmostesting/suites/IS0502Test.py
This fixes a mis-interpretation of RFC 4175. The 'top-field-first' fmtp parameter is only intended for use with signals where the vertical chrominance resolution is reduced (ie. 4:2:0). As such any comparison with the Source/Flow data could only be done by examining the video components. This could be added at a later date, but for now this just fixes the immediate problem.
=> is0502: fix bug in testing of top-field-first from SDP

nmostesting/suites/IS0502Test.py
This removes a check for an exact match between a submitted SDP file and what is returned from a configured Receiver. Whilst these should ideally be an exact match, it is possible that the Receiver may dynamically re-generate the contents of this attribute from its active media and transport parameters.
=> is0502: remove check for exact match in transport_file of Receiver

docs/1.1. Installation - Local.md, nmostesting/NMOSTesting.py, requirements.txt
Related to https://github.com/websocket-client/websocket-client/commit/efcf31b30122e05701fb3f696b029baf8faa6d8e
This sets a minimum websocket-client version to prevent compatibility issues with the callbacks.
=> requirements: add minimum websocket-client version

nmostesting/Config.py, nmostesting/IS05Utils.py
This minor PR adds parameters to allow alternative unicast/multicast destinations to be used for IS-05 testing. This is mainly intended to allow something more sensible to be configured for unicast testing.
=> config: add parameters for IS-05 stream destinations

nmostesting/Config.py, nmostesting/GenericTest.py
Reported by @mjeras
If a Node is being rebooted in order to test IS-04 discovery, the API won't be up when the pre-validation GET is performed. This flag allows it to be disabled in select circumstances to avoid this problem.
=> Add flag to disable pre-validation of API in case Node is rebooting

nmostesting/suites/IS0801Test.py
Resolves #445 
Whilst writing this I noted there are some other tests which do things like:
```
for outputInstance in outputList:
...
```
This won't cause an unhandled exception, but it may result in tests passing when there wasn't actually anything tested. I'm not familiar enough with the tests (and don't have an implementation), but it would be good if similar 'UNCLEAR' messages could be added for these tests if there simply isn't enough data exposed by the API to perform the test properly.
=> is0801: prevent testing tool accessing out of range indexes

README.md, nmostesting/IS05Utils.py, nmostesting/NMOSUtils.py, nmostesting/suites/IS0402Test.py, nmostesting/suites/IS0801Test.py, nmostesting/suites/IS0802Test.py, nmostesting/suites/is08/activation.py
Resolves #472, though requires the clocks of the Testing Tool and the Registry under test to be synchronized within ±100ms.
=> Use local timestamps in testing Query API pagination cursors

test_data/IS0401/dns_records.zone
fix #492 
Adds the TXT record to all versions despite it only be noted in v1.3
=> adding api_auth to TXT records

nmostesting/suites/IS0401Test.py
Resolves #491.
Does this need a 'More Information' link pointing somewhere?
It _could_ be a separate test case, e.g. `test_19_01`, though it would have a lot of duplicated code?
=> Add 'Not Implemented' result if attached_network_device is not present

nmostesting/suites/IS0501Test.py
We detected a couple of issues patching an `auto` value on some `transport_parameters` in our implementation and realized that that's not really covered by the test-suite yet.
Up to now the test-suite only checks that on the `/active` endpoint no `auto` value is present. It does not check what happens if `auto` is patched.
The 2 new tests patch `auto` for all possible parameters (for rtp transceivers) and checks if the values are translated in 'non-auto-values' after an activate_immediate.
If that seems to be useful for others, we could expand these tests for the other transport_types, as websocket / mqtt transports have their own '`auto`-able' parameters..
=> Added test for patching auto values

nmostesting/suites/IS0401Test.py
For Nodes which may still be in the process of starting up after issuing their first DNS query, this allows a short time for them to finish the process before beginning tests.
=> is0401: allow the Node time to react after performing a DNS query

nmostesting/Config.py, nmostesting/suites/IS0502Test.py, test_data/IS0502/audio.sdp, test_data/IS0502/video.sdp
Relates to #494, but doesn't completely resolve it. The preferred solution to this would be to have 'caps' fully populated and to determine appropriate media parameters from there.
This is a workaround for the time being, and exposes a subset of the SDP media parameters which seem most likely to need to be modified for some implementations or configurations.
=> is0502: make selected SDP media parameters configurable

nmostesting/suites/IS0501Test.py
Empty objects in `"transport_params"` are valid per the schema, and necessary for example in order to be able to express patching of only parameters of the secondary leg of a two-legged Sender or Receiver, using a request like:
```json
{
"transport_params": [
{},
{
"rtp_enabled": false
}
]
}
```
=> Add a test case for PATCH /staged with empty leg(s) in "transport_params"

nmostesting/mocks/System.py
Though clients are recommended (by description in the spec of which is considered the 'primary' path) to make requests without a trailing slash, the System API mock should accept a GET **/x-nmos/system/v1.0/global/** request (with the trailing slash) as per [URLs: Approach to Trailing Slashes: GET and HEAD requests](https://amwa-tv.github.io/nmos-system/branches/v1.0-dev/docs/2.0._APIs.html#get-and-head-requests).
Resolves #506.
=> IS-09-02: System API mock and trailing slashes

nmostesting/suites/IS0401Test.py
Relates to #517 
At least until any docs issues are resolved this removes checking for audio `grain_rate` in Sources.
=> is0401: don't check audio grain_rate due to lack of docs

nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0402Test.py, nmostesting/suites/IS0403Test.py, requirements.txt
Fix #522, by matching test code to jstakias/python-zeroconf 0.25.0, required via zeroconf-monkey 0.1.1 (https://github.com/bbc/rd-ext-lib-zeroconf-monkey/pull/1)
=> IS-04-02/-03: Fix "API authorization ('api_auth') TXT record is not one of 'true' or 'false'." with python-zeroconf 0.25.0

nmostesting/IS07Utils.py, nmostesting/suites/IS0701Test.py, nmostesting/suites/IS0702Test.py
The new test will assess the following:
- check if state messages are sent without a prior subscription command
- check if state messages are received after 1 subscription command and then after a second one is sent
- check if state messages have the correct identity
- check if state messages have minimum required timing
- check if state messages have the correct message_type
- check if state messages event_type matches the IS-04 source event_type
- checks if state messages for base event types have a valid payload
=> IS-07-02: Add test_05 which covers WebSocket state messages

nmostesting/MdnsListener.py, nmostesting/suites/IS0403Test.py
The Node may have recently been communicating with a Registry, so it makes sense to give the Node a chance to update its service info with the ver_* TXT records when switching to peer-to-peer operation (same as we do when testing that the Node correctly adopts registered operation).
We identified this case in testing, after **jstasiak/python-zeroconf** fixed the slow (5 second) `Zeroconf.close()` operation in 0.25.1, which meant that when the IS-04-03 test suite was run immediately after the IS-04-01 test suite, `IS0403Test.test_01` started failing every time.
=> IS-04-03: Allow the Node a grace period to update its service info

utilities/run-test-suites/gsheetsImport/resultsImporter.py
Uploading test results from multiple platforms can hit the google API rate limits. This patch reduces the number of reads and writes made so should reduce the chance of hitting the limits.
=> gsheetsImport: reduce the number of API calls

nmostesting/suites/IS0802Test.py
Should resolve #532. @maxwalter79, please review.
=> IS-08-02: Can't very well return e.g. `test.FAIL` if another type is expected

nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0402Test.py, nmostesting/suites/IS0403Test.py, nmostesting/suites/IS0902Test.py, nmostesting/suites/IS1001Test.py
=> ServiceInfo.address, formerly deprecated, is removed in python-zeroconf 0.27.0

nmostesting/suites/is08/outputs.py
In https://amwa-tv.github.io/nmos-audio-channel-mapping/branches/v1.0.x/docs/4.0._Behaviour.html#output-routing-constraints it specifies that if the 'routable_inputs' caps array is null then any input can be routed to the output. The code certainly expressed this intention, but as far as I can tell this would never have worked.
This fix unfortunately creates a circular dependency between the inputs and outputs files, but this is probably a minor concern here.
=> is08: fix missing method when caps array empty

nmostesting/TestHelper.py
… so that `true` doesn't compare equal to `1`, and arrays with heterogeneous types like `["foo", "bar", null]` can be compared (thus resolving one small part of #531)
This was harder to solve than it seemed, so maybe I missed something more elegant.
It would also benefit from tests...
=> Fix comparison of JSON values

nmostesting/suites/IS0801Test.py
…, which is what indicates an Output may have disconnected channels.
If `null` is not listed in `routable_inputs` but *is* accepted by the API, the FAIL message is now:
"Was able to create a forbidden route between input None and output output2 despite routing constraint."
Perhaps not perfectly clear... but better than the uncaught exception that was reported when `routable_inputs` did contain `null`.
=> Fix handling in test_13 of routable_inputs: [ ..., null ]

nmostesting/suites/is08/activation.py
They can still be stringized ints, but they can also be UUIDs, etc.
=> IS-08-01: v1.0.1 made activation ids same pattern as input and output ids

nmostesting/Config.py, nmostesting/GenericTest.py, nmostesting/NMOSTesting.py, nmostesting/suites/BCP00301Test.py
The BCP-003-01 tests currently refer to the nmos-api-security repo in their 'More Information' links which 404 as a result. This fixes the links, and includes a couple of code changes in order to make 'spec_branch' available within BCP00301Test.py. Previously this wasn't possible as the API security repo used a non-standard branch naming pattern.
=> bcp00301: update links following api-security repo split

nmostesting/NMOSTesting.py
I started looking at refactoring these (and will continue to do so), but realised that the support for existing commercial servers means we need to be careful about URL construction which should not always include 'x-nmos', and may need to include a URL path component. This makes it a little more awkward to fit into the existing testing structure.
=> is1001: disable tests until they can be refactored

nmostesting/NMOSTesting.py
I've observed the following in the logs occasionally:
```
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 361, in handle_one_request
elif self.parse_request():
File "/usr/lib/python3.6/http/server.py", line 322, in parse_request
"Bad request syntax (%r)" % requestline)
File "/usr/lib/python3.6/http/server.py", line 448, in send_error
self.log_error("code %d, message %s", code, message)
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 420, in log_error
self.log("error", *args)
File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 759, in log
host = self.headers.get("Host", "{}:{}".format(self.server.server_address[0], self.server.server_address[1]))
AttributeError: 'PortLoggingHandler' object has no attribute 'headers'
```
There is a …
=> logging: fix unhandled exception when headers missing from request

Dockerfile, nmostesting/Config.py, nmostesting/NMOSTesting.py, nmostesting/suites/BCP00301Test.py, testssl/README.md
This updates testssl to the latest released version rather than a release candidate. Tests against both a valid and invalid setup still appear to produce the correct results, but it would warrant testing against another implementation for additional confidence.
=> testssl: recommend use of latest release version

nmostesting/suites/BCP00301Test.py
BCP-003-01 tests are currently failing due to a key error when running testssl.sh
=> fix bcp tests and make them consistent with other suites

utilities/run-test-suites/gsheetsImport/resultsImporter.py
fix the following error when the results spread sheet doesn't have a blank column after the last results column:
```
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[1].updateCells: Attempting to write column: 26, beyond the last requested column of: 25', 'status': 'INVALID_ARGUMENT'}
```
=> fix insert failing when there is no blank column on the right of the sheet

nmostesting/suites/IS0501Test.py
sdpoker tests don't currently work in TLS mode as sdpoker doesn't have the CA certificate (nor have any way to pass the certificate to it).
Download the SDP files in the test to temporary files and then pass the file to sdpoker.
As a bonus this also improves the error messages when downloading the SDP file fails
=> download sdp files to pass to sdpoker

nmostesting/IS05Utils.py, nmostesting/suites/IS0501Test.py
Been meaning to look into this code for a while, just hadn't got around to deeply investigating and deciding how the test should handle checking activation when it can't easily make a change to a parameter, e.g. because the single value allowed by the **/constraints** enum is already set in **/active**.
Prompted to get into it by #584. 
This refactor implements the checks of immediate activations and both scheduled activation modes with a common function, reducing LOC by ~100. That function now performs additional checks of the activation sub-object attributes, and the number of permitted retries is reduced so that the maximum delay on a scheduled activation is reduced to a bit more than a single `Config.API_PROCESSING_TIMEOUT`. A clear `MAX_TIME_SYNC_OFFSET` of 0.1s is added, in line …
=> IS-05-01: Refactor IS-05 activation utility functions

nmostesting/IS05Utils.py
between the PATCH and getting the first results
Some devices have higher latency then others on top of adjusting for difference in system time. The API_PROCESSING_TIMEOUT is applied within the retry loop but this PR applies it before the test as well.
=> IS-05-01 Test 29/30: Allow for an API processing timeout interval

nmostesting/suites/IS0401Test.py
As per IS-04 section 2.3. APIs - Server Side Implementation Notes - Node API Senders: Use with RTP
https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.3/docs/2.3._APIs_-_Server_Side_Implementation_Notes.html#node-api-senders-use-with-rtp
Cf. IS-05-01 test_42
=> IS-04-01: RTP senders use the Content-Type 'application/sdp' for manifest_href

nmostesting/GenericTest.py
This fixes an issue with the authorization token scopes when running IS-04-01 test_04 with DNS SD disabled in the configuration.
This isn't a perfect fix as it adds 'query' scope where it may not be required for some tests. I may come back to it when I have more time.
=> token: ensure Query API is in scopes when testing without DNS-SD

docs/3.1. Testing Profiles - JT-NM TR-1001.md, nmostesting/suites/BCP00301Test.py, nmostesting/suites/IS0401Test.py, nmostesting/suites/IS0702Test.py
Updating amwa-tv.github.io links to use the new specs.amwa.tv equivalent (with AMWA ID in the path).  Please check the BCP-002-01 link in particular.  Also changed the TR-1001 link to match new jt-nm.org site.
=> Using specs.amwa.tv and updated jt-nm.org links

nmostesting/TestHelper.py, requirements.txt
Python websocket-client 0.58.0 no longer distinguishes between bound methods and simple callbacks, and always passes the `WebSocketApp`.
Fixes #605.
=> Python websocket-client 0.58.0 fix

nmostesting/TestHelper.py, requirements.txt
Python websocket-client 1.0.0 changes the way arguments are passed to the `on_close` callback (see https://github.com/websocket-client/websocket-client/commit/c414127161f6822e57177a531843c3652bc98dd6).
This caused spurious failure in **IS-07-02 test_04**: "WebSocket connection (no health cmd sent) to ws://192.168.56.1:3217/x-nmos/events/v1.0/devices/5775c3ce-310f-5036-9282-5664dc3d0ce7 was not closed after timeout".
Rather reminiscent of #605, but hopefully now that they have indicated they're adopting **semver** this shouldn't happen so often!
@lo-simon, please would you review?
=> Python websocket-client 1.0.0 fix

.github/workflows/deploy.yml
At present an issue with libffi-dev is preventing the arm/v7 build. I'll look into this when I have more time, but for now this is required to fix the other builds.
=> deploy: remove armv7 until build issue can be resolved

nmostesting/mocks/Node.py, test_data/IS0401/audio.sdp, test_data/IS0401/data.sdp, test_data/IS0401/mux.sdp, test_data/IS0401/video.sdp
Resolves #622, failures in IS-04-01 test_13 when `SDP_PREFERENCES` has been configured appropriately for a Node that analyzes and can reject an inappropriate SDP file.
Uses the same Jinja2 template mechanism as already employed for IS-05-02 (and elsewhere).
Yes, this has a little code duplication with `IS0502Test.test_18` and doesn't support Receivers that don't accept `video/raw` or `audio/L24` for example, or Receivers that check other SDP format-specific parameters (e.g. against their own Receiver caps), but that's a bigger issue, we need to introduce `video_media_type` and `audio_media_type` (or `audio_sample_depth`) etc. into `SDP_PREFERENCES` to resolve that.
=> [IS-04-01] Adapt the mock Node to config SDP_PREFERENCES

nmostesting/GenericTest.py, nmostesting/Specification.py
The primary motivation here is to thoroughly test Nodes which support several different kinds of each resource type, e.g. video/audio/ancillary data Flows, RTP and WebSocket or MQTT Receivers, etc.
Resolves #625, though will make testing take longer by default for 'big' nodes.
I'm a little unhappy with passing `test` to the "check style" `check_api_resource` just to be able to get a `MANUAL` result if there's no schema.
=> Make the auto tests more thorough by default

nmostesting/Specification.py
In PR #672 IS-04 Registration API defines a path /resource/{resourceType}/{resourceId} but does not define any methods for the parent path /resource/{resourceType}  which causes the following fail on IS-04-02 test suite: 
* Testing tool running on 'http://10.1.1.137:5000'. Version 'bfcb636'
* ERROR: '/resource/{resourceType}'
* Exiting
=> IS-04 Registration API should not use parent path /resource/{resourceType} if it doesn't exist

requirements.txt
Avoid websocket-client 1.2.2 due to https://github.com/websocket-client/websocket-client/issues/769
=> Websocket-client version 1.2.2 breaks WebSocket testing

README.md
Looks like the README is still pointing at a logo from Travis CI
=> readme: update badges to point at GitHub Actions status

nmostesting/IS05Utils.py
Resolves #631.
Failure message will now be like:
> Invalid response from single/senders/f2ef8bcd-61de-5e45-94be-cb6bb6fb7f47/constraints/, got: [{'destination_ip': {}, 'destination_port': {'enum': []}, 'rtp_enabled': {}, 'source_ip': {}, 'source_port': {}}]
There are so many different ways a _/constraints_ response could be invalid I was lazy and didn't try to make a more helpful error message identifying the particular problem...
=> Fix uncaught ValueError for invalid constraints

README.md, docs/1.0. Installation.md
Noticed this wasn't rendered correctly on specs.amwa.tv.
https://www.markdownguide.org/extended-syntax/#tables suggests pipes at start/end of rows are required by some implementations (they're optional for GitHub-Flavor Markdown).
=> Possible Markdown table syntax fix for Jekyll

nmostesting/mocks/Registry.py
Concurrent subscription requests on the mock Registry can lead to a race condition where more than one WebSocket is instantiated on the same port, leading to an exception and 501 error.  Adding a lock around the creation of the subscriptions guards against this.
=> Mock Registry: Lock around subscriptions to guard concurrent requests

nmostesting/ControllerTest.py
The mock DNS server was advertising the version of the TestingFaçade API rather than the Query API version. This stopped the DNS server from being discovered in many cases
=> Controller Tests: Fixed Query API version being advertised by mock DNS server

nmostesting/TestHelper.py
=> Log HTTP requests by the Testing Tool via TestHelper.do_request

nmostesting/Config.py, nmostesting/DNS.py
Add support for making upstream DNS requests for which the mock DNS server would otherwise send a no-such-domain (NXDOMAIN) reply via a Config setting `DNS_UPSTREAM_IP`.
Since the mock DNS server is started with the testing tool, and resolver behaviour when there are multiple DNS servers defined is inconsistent, this may help with running through multiple test suites in unicast DNS-SD mode.
----
I didn't feel the need yet to introduce `DNS_UPSTREAM_PORT` and another timeout setting for these:
```
self.upstream_port = 53
self.timeout = None
```
=> Add support for making upstream DNS requests 

nmostesting/GenericTest.py
…where we *know* it's incorrect to include the charset.
That includes [application/json](https://www.iana.org/assignments/media-types/application/json) and [application/sdp](https://www.iana.org/assignments/media-types/application/sdp), neither of which define charset as an optional or required parameter - JSON is _always_ UTF-8 and SDP charset can be mixed, and is indicated by the `a=charset:` attribute.
=> Check for unnecessary charset should only be applied to specific media types

nmostesting/suites/IS0502Test.py, nmostesting/suites/IS0802Test.py, utilities/is-05-control/is05Control.py
`assert` is a statement not a function
See https://www.flake8rules.com/rules/E275.html
and https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-assert_stmt
=> Fix flake8 E275 missing whitespace after keyword

nmostesting/ControllerTest.py, nmostesting/mocks/Node.py, nmostesting/suites/IS0404Test.py, nmostesting/suites/IS0503Test.py
This pull request aims to improve controller compatibility:
- In the IS-04 Controller tests where a Sender is put offline/back online the Senders on the mock Node are now removed/added to be consistent with the mock Registry
- In the IS-05 Controller tests Receivers that do not have a connection API are no longer added to the mock Node (i.e. only connectable receivers appear on the mock Node)
- In the IS-05 Controller tests, a guard has been put in when checking for double patch requests so that Sender patches aren't confused with Receiver patches (i.e. when patching both the Sender and Receiver, it is now no longer interpreted as a double Receiver patch).
- If a `sender_id` has not being set in the Receiver patch requests this results in a warning, rather than a failure (in the current …
=> Controller Test patches for improved Controller compatibility

nmostesting/NMOSTesting.py, nmostesting/templates/result.html
Should resolve #702.
We could do better with more refactoring. Right now, the caching of spec/endpoint data in the form when moving between different test suites is a little awkward since it's done by index not by API, e.g. move from IS-08-01 (which just needs the Channel Mapping API) to IS-08-02 (which needs Node API and Channel Mapping API, in that order) and the cached form content for the Channel Mapping API is used to populate the Node API fields.
=> [IS-08] Selector fix

docs/2.8. Usage - Testing Controllers.md, nmos-testing-facade.py, nmostesting/Config.py, nmostesting/ControllerTest.py, nmostesting/TestHelper.py, nmostesting/mocks/Node.py, nmostesting/mocks/Registry.py, nmostesting/suites/IS0404Test.py, testingfacade/templates/index.html
Updates required to run the NMOS Controller tests in secure mode. These include:
- Correctly forming secure URLs within the ControllerTest.py base class
- Implementing secure version of WebSocket server for mock Registry subscriptions
- Fix of bug in mock Node which could have led to spurious failure of IS-05 Controller test_02 (in both secure and insecure modes)
=> Secure Controller Testing

nmostesting/Patches.py, nmostesting/TestHelper.py, requirements.txt
Cherry-pick https://github.com/AMWA-TV/nmos-testing/pull/715/commits/8038da92e3b1035dce17ebdcc67066efc1e5d6c8
> the jsonref 1.0.0 release includes https://github.com/gazpachoking/jsonref/pull/43... it's not clear from https://github.com/AMWA-TV/nmos-testing/pull/106 why we needed to set `cache_results=False`) and the jsonref 1.0.0 makes significant changes to the way `$ref`ed schemas are cached, so I can't immediately tell if this is going to cause us a problem.
but I think we should go for it and fix any issues rather than pin `jsonref` back to pre-1.0.0.
=> Patch jsonref dependency

nmos-testing-facade.py, nmostesting/TestHelper.py
... in order to meet the requirements of the [Fetch spec for CORS requests](https://fetch.spec.whatwg.org/#http-requests), as identified in #722.
=> Add an Origin: null header to all requests from the testing tool

nmostesting/suites/IS0401Test.py
Advertise the mDNS sender to allow Node to find it for obtaining the SDP. The problem seems while running testsuite and Node on a different host.
=> fix IS-04-01 test_13

nmostesting/suites/BCP0060102Test.py
In test_01 and test_02 ensure there is at least one "video/raw" Sender or Receiver
=> BCP-006-01 Controller Test: ensure example "video/raw" Senders/Receivers in tests

nmostesting/suites/BCP0060101Test.py, nmostesting/suites/BCP0060102Test.py, nmostesting/suites/IS0502Test.py
Cf. https://github.com/AMWA-TV/bcp-006-01/pull/24
A Node that only implements (i.e. is tested against) IS-04 v1.2 will get one **Fail** and a couple of **Not Applicables** with explanations of what will be required when they implement IS-04 v1.3.
=> [BCP-006-01] Require IS-04 v1.3

nmostesting/suites/IS0801Test.py
There are 6 possible test results besides green "Pass" (PASS) and red "Fail" (FAIL)...
https://github.com/AMWA-TV/nmos-testing/blob/eef5fabf26f2bc6af0054ac7327059284c305b20/nmostesting/TestResult.py#L22-L30
As far as I understand, the yellow "Not Implemented" (OPTIONAL) and "Warning" (WARNING) refer to unimplemented optional and recommended features in the thing under test. For tests that cannot be run because the thing under test (perhaps just temporarily) doesn't expose the feature (e.g. a transmit-only thing may have no Receiver resources), we have yellow "Could Not Test" (UNCLEAR). For test cases that do not apply to the version of API under test, we have grey "Not Applicable" (NA). For things that cannot be tested due to other testing tool config (e.g. secure/auth/DNS-SD options) we …
=> [IS-08] UNCLEAR rather than NA

nmostesting/Config.py, nmostesting/GenericTest.py, nmostesting/suites/IS0402Test.py
we changed the repo names about 1 year ago, see https://amwatv.slack.com/archives/C012YDDREVB/p1640264384096200
=> use new repo names

nmostesting/suites/BCP0060102Test.py
- Relaxed version check on BCP-006-01 Controller tests to allow any version as any version of Query API *could* implement Receiver Capablities
- Updated Test Facade Question with instructions for testers unable to complete the requested tests
=> BCP-006-01 Controller Tests Updated Version Check and Test Facade Instructions

.deploy/docker-compose.yml, .github/workflows/deploy.yml
When forking the repo and running the Actions, using GitHub DOCKER_USERNAME for the docker image is handy.  Since a docker account is needed to run the Action, there should not be a case where we need a default value.
=> Use github DOCKER_USERNAME secret for docker image name

nmostesting/NMOSTesting.py, nmostesting/TestHelper.py, nmostesting/mocks/Auth.py, nmostesting/suites/BCP00301Test.py
@lo-simon worked out what was up with the mock servers rejecting TLS connections with `ENABLE_HTTPS = True`. The `ssl.create_default_context()` function is by default only appropriate for client-side, authenticating connections to servers. So our mocks need to explicitly specify `purpose=ssl.Purpose.CLIENT_AUTH`.
I conjecture but haven't proven that this may only be a problem since 3.10, per this note in the docs:
> _Changed in version 3.10:_ The context now uses `PROTOCOL_TLS_CLIENT` or `PROTOCOL_TLS_SERVER` protocol instead of generic `PROTOCOL_TLS`.
=> Fix mock servers with ENABLE_HTTPS = True on Windows

nmostesting/NMOSTesting.py, nmostesting/templates/index.html, nmostesting/templates/result.html
so we can see it before running a test suite!
(cf. b493b79a3e6dfd4c11e25fddf827e77c9c18887d)
=> index: display configuration in HTML output

nmostesting/TestHelper.py
The explicit passing of coroutine objects to asyncio.wait() has been deprecated since Python 3.8, and has now been removed in Python 3.11.
=> Fix "Passing coroutines is forbidden, use tasks explicitly" error

.github/workflows/deploy.yml, Dockerfile
Changes :
- Add a shallow clone of the git repo (image size goes from 256.8MB to 257.97MB. This allows the Python code that displays the version of the test suite to work the same for a local repo and a docker container.
- Add tags for branches using commit SHA.  
- Updated the versions of the GitHub actions to be the latest versions.
- Tested on NMOS Testbed.
=> Fix for version display in Docker

nmostesting/GenericTest.py
`auto_*` tests collect cache while going through resources in each API. The issue is that API lexicographic order matters: if an API has less resources than any of previous APIs, `auto_*` take resource IDs from the cache and fail, although the API itself doesn't even list these IDs.
The fix clears the cache after going though each API.
=> Clear resource IDs cache before autotesting each API

README.md, nmostesting/NMOSUtils.py, nmostesting/suites/IS0502Test.py, nmostesting/suites/IS0702Test.py, nmostesting/suites/IS0802Test.py, nmostesting/suites/IS1101Test.py
Fixes the test that searches for IS-11 control advertisement in IS-04 APIs. For instance, this test fails with the following `controls`:
```
"controls": [
{
"href": "http://192.168.228.40:3215/x-nmos/connection/v1.0",
"type": "urn:x-nmos:control:sr-ctrl/v1.0"
},
{
"href": "http://192.168.100.40:3215/x-nmos/connection/v1.0",
"type": "urn:x-nmos:control:sr-ctrl/v1.0"
},
{
"href": "http://192.168.228.40:3215/x-nmos/connection/v1.1",
"type": "urn:x-nmos:control:sr-ctrl/v1.1"
},
{
"href": "http://192.168.100.40:3215/x-nmos/connection/v1.1",
"type": "urn:x-nmos:control:sr-ctrl/v1.1"
},
{
"href": "http://192.168.228.40:3216/x-nmos/events/v1.0",
"type": "urn:x-nmos:control:events/v1.0"
},
{
"href": "http://192.168.100.40:3216/x-nmos/events/v1.0",
"type": "urn:x-nmos:control:events/v1.0"
},
{ …
```
=> Check IS-11 control advertisement like other test suites do

nmostesting/Config.py, nmostesting/IS11Utils.py, nmostesting/suites/IS1101Test.py
Adding 'valid' verification to Fix issue https://github.com/AMWA-TV/nmos-testing/issues/790
Add usage of STABLE_STATE_DELAY from Config.py
A few failure comment clarifications
=> [IS-11] Adding 'valid' verification to Fix issue 790

utilities/dut-data-exporter/dutDataExporter.py
The lint action has just switched from flake8 6.0.0 (pycodestyle 2.10) to flake8 6.1.0 (pycodestyle 2.11) and that seems to mean it's reporting [E721](https://www.flake8rules.com/rules/E721.html) where it wasn't before.
Ah yes, it's in the changelog for pycodestyle:
> * E721: adjust handling of type comparison.  Allowed forms are now
>  ``isinstance(x, t)`` or ``type(x) is t``.  PR #1086, #1167.
https://github.com/PyCQA/pycodestyle/blob/abe69bb9e1f358d0f1ba71034bc66a43725d28c7/CHANGES.txt#L12-L13
=> Fix flake8/pycodestyle E721 do not compare types

.github/workflows/lint.yml
Trying this out due to https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> Bump Node 12.x to Node 16.x

Dockerfile, docs/1.1. Installation - Local.md, nmostesting/suites/IS0401Test.py, requirements.txt
Resolve #828.
Could have just put `strict=False` on all the `register_service` calls that advertise the Registration API, but figured might as well pass `False` only when we believe that's necessary: for `_nmos-registration._tcp` and not for `_nmos-register._tcp`.
=> python-zeroconf 0.75.0 strict=False for _nmos-registration._tcp

nmostesting/suites/BCP00301Test.py
So that same one is used by Python tests and testssl.sh tests
=> Pass IP address of API under test to testssl.sh

nmostesting/Config.py, nmostesting/NMOSTesting.py
This gives the API or client under test a chance to use the mock services before any test case is run.
=> Mocks warm up

nmostesting/IS11Utils.py, nmostesting/suites/IS1101Test.py
- Fix Test 4.4 to support devices without output
- Add a few functions to IS11Utils to reduce code repetition
=> [IS-11] - Fix Test 4.4 to support devices without output

nmostesting/GenericTest.py
- This removes the current limitation of a single URL parameter in an endpoint URL when running auto tests.
- This is a problem for the emerging IS-14 API as this has endpoints with two URL parameters.
- This code is generalized to allow any number of URL parameters, simplifying the existing implementation.
=> Allow multiple URL parameters in auto tests endpoints.

nmostesting/suites/IS1101Test.py
Use the GenericTest::do_request instead of the raw request to enable HTTPS and AUTH support
=> Fix IS-11 test_02_03_04

nmostesting/suites/IS0501Test.py
per https://specs.amwa.tv/is-05/releases/v1.1.2/docs/Controllers.html
Controllers performing requests other than GET or HEAD (i.e PUT, POST, DELETE, OPTIONS etc.) MUST use URLs with no trailing slash present.
Currently, test_11_02 and test_12_02 will fail on a node that returns 405: method not allowed for a PATCH on the /staged/ endpoint
=> IS0501Test.py: remove trailing slash from /staged endpoint for PATCH

nmostesting/suites/IS0501Test.py
As per https://specs.amwa.tv/is-05/releases/v1.1.2/docs/Behaviour_-_RTP_Transport_Type.html#receiver-parameter-sets, `multicast_ip` is part of its own parameter set, not the Core Parameters.
=> [IS-05-01] test_11 and test_12 refactor to account for "Multicast Parameters" RTP Receiver Parameter Set

nmostesting/NMOSTesting.py
- This linting error has been trapped by the upgrade of flake8 from 7.1.2 -> 7.2.0
- This error has been extant for 5+ years and has only trapped by the upgrade to flake8.
- Remove `global CMD_ARGS` statement as it is unused: name is never assigned in scope.
- This error will fail the linting of all current pull requests that are in flight.
=> Fix linting error due to upgrade of flake8

nmostesting/NMOSTesting.py
- IS-12 PR introduced `urlpath` command line argument
- non-interactive tests have a `urlpath` typo causing crash when run
=> Bug Fix: Fix non-interactive tests

nmostesting/suites/IS1101Test.py
- fixes the namespace to match with Sender Capabilities.
- fixes some UNCLEAR errors to proper FAIL or DISABLED ones
- fix state comparison state != "OK" to state != "unconstrained"
=> Fixes for ipmx testing

nmostesting/Config.py, nmostesting/ControllerTest.py, nmostesting/NMOSTesting.py, nmostesting/TestingFacadeUtils.py, nmostesting/suites/BCP0060102Test.py, nmostesting/suites/IS0404Test.py, nmostesting/suites/IS0503Test.py, nmostesting/suites/MS0501Test.py
- The Testing Facade was developed to allow user interactive testing of Controllers with the `ControllerTest` class.
- However, applications of the Testing Facade have extended beyond Controller testing.
- For instance, it is now used in the MS-05/IS-12 test suite to guide invasive testing of MS-05 Device Models.
- To decouple the MS-05/IS-12 test suite from the `ControllerTest` class, the Testing Facade functionality has been refactored into a `TestingFacadeUtils` class.
- Associated API keys have been renamed from `CONTROLLER_TEST_API_KEY` to `TESTING_FACADE_API_KEY`.
- Associated spec keys have been renamed from `controller-tests` to `testing-facade`.
- All affected test suites have been tested, namely:
- IS-04-04
- IS-05-03
- BCP-006-01-02
- IS-12
=> Refactor Testing Facade out of Controller Tests into utility class

nmostesting/NMOSTesting.py
* controller-test is the old spec_key
* the testing-facade refactoring changed the name to "testing-facade"
* update the IS-14 test definition accordingly
=> IS-14: Change spec_key from controller-test to testing-facade
